server:
  port: 2003
spring:
  application:
    name: seata-account-2003
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: qyc_tx_group
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/seata_account
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis.xml