server:
  port: 8003
spring:
  profiles:
    active: dev
  application:
    name: pay-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        group: devGroup
        namespace: c2567bef-205d-47ed-8f76-23d000ee0c69


management:
  endpoints:
    web:
      exposure:
        include: "*"