server:
  port: 81
spring:
  application:
    name: order81
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos地址
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
#暴露
management:
  endpoints:
    web:
      exposure:
        include: "*"

#开启sentinel对feign的支持
feign:
  sentinel:
    enabled: true
